### ISSUE TITLE
implement repository fixes already applied to SPECFEM3D 

### ISSUE THREAD

**Issue by bch0w** [SPECFEM/specfem2d#1163]
Related to organization of SPECFEM repository that was addressed during the 2022 Developers Workshop in Toronto.

Pull requests in SPECFEM3D (https://github.com/SPECFEM/specfem3d/pull/1556, https://github.com/SPECFEM/specfem3d/pull/1545, https://github.com/SPECFEM/specfem3d/pull/1542, https://github.com/SPECFEM/specfem3d/pull/1528, https://github.com/SPECFEM/specfem3d/pull/1525) cleaned up some of the main directory structure and implemented some useful repository additions. To keep things on track in all versions of SPECFEM, we will want to do the same for SPECFEM2D.

### Checklist of fixes to be applied:
- [ ] Implement a bug report template https://github.com/SPECFEM/specfem3d/pull/1528
- [ ] Adjust language in README https://github.com/SPECFEM/specfem3d/pull/1525
- [ ] ~~Remove version numbers from source code https://github.com/SPECFEM/specfem3d/pull/1545~~
- [ ] Update all references to GitHub web addresses to new SPECFEM organization https://github.com/SPECFEM/specfem3d/pull/1556
- [ ] Rename/move long filenames in main directory https://github.com/SPECFEM/specfem3d/pull/1542

#### Comments
- I can take care of this for SPECFEM3D_GLOBE as well, after I finish with SPECFEM2D
- ~~@gassmoeller did you have a script to handle https://github.com/SPECFEM/specfem3d/pull/1545? I can write something up but didn't want to reinvent the wheel if you already had something working~~ nevermind, I was able to quickly write up a short script to do this
- Anything missing that took place in SPECFEM3D but is not listed in the above checklist?

**Comment by bch0w** [comment]
Woops, didn't see that @gassmoeller already implemented most of this a while back!

**Comment by gassmoeller** [comment]
Just to keep track where the changes happened, version numbering was reworked in #1158.
