### ISSUE TITLE
How to change the interface of step (structure) model 

### ISSUE THREAD

**Issue by rashi-13** [SPECFEM/specfem2d#1167]
I am trying to generate the grid for a step structured model with 5 layers. 
The path given for interface is linked to EXAMPLE directory and when the values are being modified over there, mesh generation is not happening.

**Comment by danielpeter** [comment]
not sure what you refer to by step structured model. maybe you could provide your setup in `Par_file` that you tried out? 

by default, the interface file will be searched in the `./DATA/` folder. so, when you specify in `Par_file`:
```
# file containing interfaces for internal mesh
interfacesfile                  = ../EXAMPLES/simple_topography_and_also_a_simple_fluid_layer/DATA/interfaces_simple_topo_curved.dat
```
it will try to open the file in folder `./DATA/../EXAMPLES/simple_topography_and_also_a_simple_fluid_layer/DATA/`. 

obviously, you could also just copy the interfaces file into your current work directory folder `./DATA/` and use a setting like:
```
# file containing interfaces for internal mesh
interfacesfile                  = interfaces_simple_topo_curved.dat
```
and then modify the file content accordingly in your `./DATA/` folder.

**Comment by rashi-13** [comment]
i figured it out. Thank you so much for replying promptly.
