### ISSUE TITLE
Partitioning Problems with External Meshing in Cubit?

### ISSUE THREAD

**Issue by ARBolton96** [SPECFEM/specfem2d#1174]
Hello,

I'm running a very simplified test model meshed in Cubit with SpecFEM2D and I'm running into some issues with the partitioning. Using the `cubit2specfem2d.py` journal file given in the SpecFEM2D utils directory (very helpful by the way!), I was able to create the necessary mesh files and set up a SpecFEM simulation.

However, when I run this model over multiple processors, this occurs:
![mymesh](https://user-images.githubusercontent.com/64854801/212947066-d0f16a38-00b7-4d8b-8b85-22954151aa1c.png)

All the energy in the simulation stays within the source layer! There is no transmission into the deeper model, which I have verified with the station configuration in the above image, as well as the output postscript files.

If I run this same exact mesh over a single processor (thus avoiding mpirun commands), I get this:

![mymesh_oneproc](https://user-images.githubusercontent.com/64854801/212952340-9255ed28-7902-492c-9ff2-cf3a6cf3d5fb.png)

Transmission into the subsurface!

I then went to the provided `EXAMPLES` directory and looked at the `salt_dome_CUBIT_mesh_from_Ronan_Madec/Stacey_normal_fluid_solid` (full salt dome model with overlying water layer), and edited the `Par_file` to run over multiple processors. The results were:

![saltmesh](https://user-images.githubusercontent.com/64854801/212951842-5ea18b45-d265-4476-b5b5-8637e63f4127.png)

Once again perfect transmissions, and this time over multiple processors! Very perplexing to me.

I am assuming the problem I'm encountering is with the partitioning of the simple mesh I've built. Have others encountered this issue, or have any general guidance? I can provide any of the SpecFEM input files or my Cubit mesh and `cubit2specfem.py` files, if necessary. Thanks!

**Comment by AbolfazlKhanMo** [comment]
Hey,
This looks a little bit odd! Can you please provide your mesh's cubit _journal_ file (or .py file)? If not, make sure you're merging all volumes (_merge vol all_) and imprinting them (_imprint vol all_) before starting the meshing process.
Hope this helps!

**Comment by ARBolton96** [comment]
Hot dog!!! That is exactly what I was missing! Thank you so much @AbolfazlKhanMo, that was so very helpful. I completely missed those commands in the salt dome example.
