### ISSUE TITLE
external tomography file usage

### ISSUE THREAD

**Issue by danielpeter** [SPECFEM/specfem2d#1175]
### Discussed in https://github.com/orgs/SPECFEM/discussions/1586

<div type='discussions-op-text'>

<sup>Originally posted by **DanBrox** February 28, 2023</sup>
Trying to use an external 2D velocity model in SPECFEM2D by setting MODEL = external in the Par file.  When I use the attached tomo_file.xyz

[tomo_file.txt](https://github.com/SPECFEM/specfem3d/files/10854513/tomo_file.txt)

I get simulation results where the P-wave velocity appears to be larger than anticipated:

![proc000000_vp](https://user-images.githubusercontent.com/46611376/221971646-277f7ea0-c610-4cee-a4a5-152fa44175ac.jpg)

Also, when I try plotting the velocity model using the 'Visualizations' tool, it shows the following min/max P-wave velocity information which doesn't seem to agree with the tomo_file.xyz.  Suggestions as to what the problem is?

python3 plot_model_from_gll_or_binary_file.py proc000000_vp.bin
input file:  proc000000_vp.bin

reading in file:  proc000000_vp.bin

model:  proc000000_vp
  values min/max =  13866.453 / 13866.883

reading in position files...
proc000000_x.bin
proc000000_z.bin

mesh dimensions: x min/max =  0.0 / 6000.0
                 z min/max =  0.0 / 4000.0

plotting model...
  plotted as  proc000000_vp.jpg

done

</div>

**Comment by danielpeter** [comment]
a short note on using tomographic models: 

In the `DATA/Par_file`, you should set 
```
MODEL                            = default
``` 
and define a material with a negative material_type number, e.g., like
```
# number of model materials
nbmodels                        = 1
# available material types (see user manual for more information)
# ..
1 -1 0 0 1000.0 0 0 0 0 0 0 0 0 0 0
```
together with the tomo file specified like
```
# external tomography file
TOMOGRAPHY_FILE                 = ./DATA/tomo_file.txt
```

The Vs value above of a `1000.0` is set arbitrarily, but should be either zero (0.0) or a positive value to distinguish between an acoustic or elastic region, respectively. The velocities specified in the tomo file will be overimposed on this material.

The `nbregions` section then needs to use the material number `1` for the region where the tomography model should be applied. This can either be the whole region or only a subregion, where the other mesh regions will take the velocities from another additional material specified in the `nbmodels` section.

**Comment by himansh78** [comment]
Hey, following this issue,  I am trying find the guide on how to use tomo file in specfem2D, but the manual doesn't seem to be having any information on that, could you please point me to the right resource.
I am doing forward simulations for different tomographic domains.

**Comment by danielpeter** [comment]
there isn't much more to read about, but it's mentioned here:
https://specfem2d.readthedocs.io/en/latest/03_mesh_generation/#notes-about-datapar_file-parameters

**Comment by DanBrox** [comment]
Solved the problem.  Thanks

**Comment by himansh78** [comment]
> there isn't much more to read about, but it's mentioned here: https://specfem2d.readthedocs.io/en/latest/03_mesh_generation/#notes-about-datapar_file-parameters

Thanks. Is there any example simulation using tomofile, that would help me a lot.

**Comment by danielpeter** [comment]
regarding an example, how about: 
[EXAMPLES/tomographic_ocean_model](https://github.com/SPECFEM/specfem2d/tree/master/EXAMPLES/tomographic_ocean_model)

for the mesh regions, you have a material number for your "tomographic" material, say 1, and another material for your other region, say 2. then you can do:
```
nbregions                       = 2              # then set below the different regions and model number for each region
# format of each line: nxmin nxmax nzmin nzmax material_number
1            100       1          50        1
1            100       51        100        2
```
to take the "tomography" part in the lower half, and the other material in the upper one.

**Comment by himansh78** [comment]
Thanks a lot! this is what I needed. appreciate your prompt help.
