### ISSUE TITLE
Does SPEFCEM2D scale kernels?

### ISSUE THREAD

**Issue by AbolfazlKhanMo** [SPECFEM/specfem2d#1188]
Hi everyone,

I did a little experiment; two exact simulations but two different source amp_factor. The kernels are precisely the same. 

**src_amp_factor  = 1e20**
![proc000000_rhop_alpha_beta_kernel_1E20](https://github.com/SPECFEM/specfem2d/assets/82332435/78b8a905-c63f-40ac-b8ee-4958f96eab3e)

**src_amp_factor  = 1e10**
![proc000000_rhop_alpha_beta_kernel_1E10](https://github.com/SPECFEM/specfem2d/assets/82332435/15050a64-e915-4486-a382-ab2c78d9cf14)

Why are these kernels the same? Shouldn't they be different?
Does _SPECFEM2D_ scale the kernels based on the source amplification factor?

**Comment by danielpeter** [comment]
As a general remark, the sensitivity kernels depend on the adjoint source(s) you use. 

in your case, I assume that you used adjoint sources for traveltime misfits. for such traveltime sensitivity kernels, the sensitivity is independent of the source amplitude. That is, you did a nice validation test to check whether the numerical results are indeed independent of the source amplitude factor :)
